---
# tasks file for configure
- name: Update pool
  ansible.builtin.command:
    cmd: timedatectl set-ntp true
  tags:
    - configure

- name: Update timezone
  ansible.builtin.command:
    cmd: timedatectl set-timezone "{{ ntpd_timezone }}"
  tags:
    - configure
