---
# tasks file for requirements

- name: Add kubernetes repository
  ansible.builtin.template:
    src: 'kubernetes.repo.j2'
    dest: /etc/yum.repos.d/kubernetes.repo
  tags:
    - requirements    