---
- hosts: elastic
  roles:
     - elastic/requirements
     - disk/configure
     - elastic/firewall
     - elastic/install
     - elastic/ca
     - elastic/ca-easyrsa
     - elastic/plugin
     - elastic/configure
     - elastic/security


