---
# tasks file for install

- name: Ensure group {{ zk_group}} exists
  group:
    name: "{{ zk_group}}"
    state: present
  tags:
    - install

- name: Add the user {{ zk_user}}
  user:
    name: "{{ zk_user}}"
    comment: zookeeper service user
    group: "{{ zk_group}}"
    shell: "/usr/sbin/nologin"
  tags:
    - install


- name: create data directory
  file:
    path: "{{ zk_data_path}}"
    state: directory
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
  tags:
    - install


- name: create zookeeper home directory
  file:
    path: "{{ zk_home}}"
    state: directory
    owner: "{{ zk_user}}"
    group: "{{ zk_group}}"
  tags:
    - install

- name: create minio conf directory
  file:
    path: "{{ zk_conf}}"
    state: directory
    owner: "{{ zk_user}}"
    group: "{{ zk_group}}"
  tags:
    - install

- name: Copy file server
  copy:
    src: "{{ local_install_dir}}/kafka_2.13-{{ zookeeper_version }}.tgz"
    dest: "/tmp"
    owner: "{{ zk_user}}"
    group: "{{ zk_group}}"
  tags:
    - install  

- name: Extract kafka into {{ zk_home}}
  unarchive:
    src: "/tmp/kafka_2.13-{{ zookeeper_version }}.tgz"
    dest: "{{ zk_home}}"

- name: Populate service facts
  service_facts:    
  tags:
    - install  

- name: stop service 
  service: 
    name: "zookeeper"
    state: stopped 
  when: ansible_facts.services["zookeeper.service"] is defined    
  tags:
    - install  

- name: Configure zookeeper.service
  template:
    src: "zookeeper.service.j2"
    dest: "/etc/systemd/system/zookeeper.service"
  tags:
    - install

- name: issue daemon-reload to pick up config changes
  systemd:
    daemon_reload: yes
  tags:
    - install  

- name: enable service 
  service: 
    name: "zookeeper"
    enabled: yes
    state: started
  tags:
    - install  

