---
# tasks file for configure

- name: Populate service facts
  service_facts:    
  tags:
    - configure

- name: Configure kibana module
  template:
    src: "kibana-xpack.yml.j2"
    dest: "/etc/metricbeat/modules.d/kibana.yml"
  when: ansible_facts.services['kibana.service'] is defined    
  notify:
    - restart
  tags:
    - configure  

- name: Configure metricbeat module
  template:
    src: "metricbeat-xpack.yml.j2"
    dest: "/etc/metricbeat/modules.d/metricbeat.yml"
  when: ansible_facts.services['metricbeat.service'] is defined    
  notify:
    - restart
  tags:
    - configure  

- name: Configure elasticsearch module
  template:
    src: "kibana-xpack.yml.j2"
    dest: "/etc/metricbeat/modules.d/elasticsearch.yml"
  when: ansible_facts.services['elasticsearch.service'] is defined    
  notify:
    - restart
  tags:
    - configure  

- name: Configure metricbeat.yml
  template:
    src: "metricbeat.yml.j2"
    dest: "/etc/metricbeat/metricbeat.yml"
  notify:
    - restart
  tags:
    - configure  

- name: create certs directory 
  file:
    path: /etc/metricbeat/certs
    state: directory
  notify:
    - restart
  tags:
    - configure

- name: Copy root ca file 
  copy:
    src: "{{ local_install_dir}}/{{ es_clustername}}.crt"
    dest: "/etc/metricbeat/certs/{{ es_clustername}}.crt"
  notify:
    - restart
  tags:
    - configure
