---
# tasks file for install

- name: create kubernetes directory 
  delegate_to: localhost
  file:
    path: "{{ item}}"
    state: directory
  with_items:
    - "{{ local_install_dir}}/kubernetes"
    - "{{ local_install_dir}}/kubernetes/{{ k8_cluster_name }}"
  tags:
    - install


- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: 
    cmd: "swapoff -a"
  tags:
    - install  

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  tags:
    - install  

- name: Disabling SELinux state
  selinux:
    state: disabled
  tags:
    - install  

- name: Print the changes in Configuration file 
  command: grep SELINUX /etc/sysconfig/selinux
  register: sevalue
  tags:
    - install  

- debug:
    var: sevalue.stdout_lines        
  tags:
    - install  


- name: Install containerd 
  yum:
    name: [containerd]
  tags:
    - install  

- name: Install docker-ce
  yum:
    name: [docker-ce]
  notify: start docker
  tags:
    - install  

- name: Enable docker service
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started
  notify: start docker
  tags:
    - install  

- name: Install kubernetes packages
  yum:
    name: [kubelet,kubeadm,kubectl]
    disable_excludes: kubernetes
  notify: start kubelet  
  tags:
    - install  

- name: Enable kubelet service
  ansible.builtin.service:
    name: kubelet
    enabled: yes
  notify: start kubelet  
  tags:
    - install  

