---
# tasks file for ca

- name: check if ca file exists
  stat: 
    path: "/etc/elasticsearch/certs/{{ es_clustername }}.p12"
  register: ca_p12

- name: create certs directory 
  file:
    path: /etc/elasticsearch/certs
    state: directory
    owner: elasticsearch
    group: elasticsearch
  tags:
    - ca

- name: Run command if ca.p12 does not exist
  ansible.builtin.command:
    cmd: /usr/share/elasticsearch/bin/elasticsearch-certutil ca --out "/etc/elasticsearch/certs/{{ es_clustername }}.p12" --pass "{{es_clustername}}"
    creates: "/etc/elasticsearch/certs/{{ es_clustername }}.p12"

- name: Change CA owner
  ansible.builtin.file:
    path: "/etc/elasticsearch/certs/{{ es_clustername }}.p12"
    owner: elasticsearch
    group: elasticsearch

- name: Fetch ca 
  ansible.builtin.fetch:
    src: "/etc/elasticsearch/certs/{{ es_clustername }}.p12"
    dest: "{{ local_install_dir }}"/{{ es_clustername }}.p12
