---
# tasks file for configure

- name: Configure server conf
  template:
    src: "{{ ka_config_file }}"
    dest: "{{ ka_conf}}/server.properties"
    owner: "{{ ka_user}}"
    group: "{{ ka_group}}"
  tags:
    - configure

- name: enable service 
  service: 
    name: "kafka"
    enabled: yes
    state: started
  tags:
    - configure
