---
# tasks file for firewall
- firewalld:
    port: 53/udp
    permanent: true
    state: enabled
    immediate: true
  tags:
    - firewall  

- firewalld:
    port: 53/tcp
    permanent: true
    state: enabled
    immediate: true
  tags:
    - firewall  
