er_user: "easyrsa"
er_group: "easyrsa"
er_home: "/opt/easyrsa"
er_conf: "/etc/easyrsa"
er_port: "2181"
er_port_mgt1: "2888"
er_port_mgt2: "3888"
er_data_path: "{{ mount_logical_volume}}/easyrsa"
er_config_file: "easyrsa.properties.j2"
er_version: "3.0.8"
er_rootca: "easyrsa-rootca"
