k8_role_master: false
k8_role_worker: false
k8_role_node: false
k8_cluster_name: "mykubernetescluster"
k8_podnet_flannel: true
k8_podnet_weave: false

# Master nodes firewall ports
k8s_master_ports:
    - 6443
    - 2379-2380
    - 10250
    - 10251
    - 10252
    - 10255

# Worker nodes firewall ports
k8s_worker_ports:
    - 6783
    - 10250
    - 10255
    - 30000-32767

k8s_flannel_ports:
    - 8285
    - 8472
