---

- name: Check for pki dir
  stat: path="{{ local_install_dir}}/{{es_clustername}}/kibana-encryptedSavedObjects"
  register: encryption_strings
  tags:
    - configure


- name: encryption_string encryptedSavedObjects
  set_fact:
    encryptedSavedObjects: "{{ lookup('password', '{{ local_install_dir}}/{{es_clustername}}/kibana-encryptedSavedObjects chars=ascii_lowercase,digits length=24') }}"  
  when: not encryption_strings.stat.exists
  tags:
    - configure

- name: encryption_string reporting
  set_fact:
    reporting: "{{ lookup('password', '{{ local_install_dir}}/{{es_clustername}}/kibana-reporting chars=ascii_lowercase,digits length=24') }}"  
  when: not encryption_strings.stat.exists
  tags:
    - configure

- name: encryption_string security
  set_fact:
    security: "{{ lookup('password', '{{ local_install_dir}}/{{es_clustername}}/kibana-security chars=ascii_lowercase,digits length=24') }}"  
  when: not encryption_strings.stat.exists
  tags:
    - configure


# tasks file for configure
- name: Configure kibana.yml
  template:
    src: "{{ kbn_kibana_yml }}"
    dest: "/etc/kibana/kibana.yml"
    owner: kibana
    group: kibana
  notify:
    - restart
  tags:
    - configure  

- name: create certs directory
  file:
    path: "/etc/kibana/certs"
    state: directory
    owner: kibana
    group: kibana
  notify:
    - restart
  tags:
    - configure  

- name: Copy CA file 
  copy:
    src: "{{ local_install_dir }}/{{ es_clustername }}/certs/{{ er_rootca }}.crt"
    dest: "/etc/kibana/certs/{{ er_rootca }}.crt"
    owner: kibana
    group: kibana
  when: es_tls == true  and ca_provider== "easyrsa"
  notify:
    - restart
  tags:
    - configure

- name: Copy kibana cert file 
  copy:
    src: "{{ local_install_dir }}/{{ es_clustername }}/certs/{{ kbn_hostname}}.crt"
    dest: "/etc/kibana/certs/{{ kbn_hostname}}.crt"
    owner: kibana
    group: kibana
  when: es_tls == true  and ca_provider== "easyrsa"
  notify:
    - restart
  tags:
    - configure

- name: Copy kibana key file 
  copy:
    src: "{{ local_install_dir }}/{{ es_clustername }}/certs/{{ kbn_hostname}}.key"
    dest: "/etc/kibana/certs/{{ kbn_hostname}}.key"
    owner: kibana
    group: kibana
  when: es_tls == true  and ca_provider== "easyrsa"
  notify:
    - restart
  tags:
    - configure

