---
# tasks file for configure

- name: Check for pki dir
  stat: path="{{ er_home}}/bin/pki/ca.crt"
  register: p
  tags:
    - configure

- name: Create vars
  template:
    src: vars.j2
    dest: "{{ er_home}}/bin/vars"
  tags:
    - configure  

- name: init pki
  shell: 
    cmd: ./easyrsa init-pki
    chdir: "{{ er_home}}/bin"
  when: not p.stat.exists
  tags:
    - configure


- name: build-ca
  shell: 
    cmd: ./easyrsa build-ca nopass
    chdir: "{{ er_home}}/bin"
  when: not p.stat.exists
  tags:
    - configure


- name: create certs directory 
  delegate_to: localhost
  file:
    path: "{{ local_install_dir }}/{{ es_clustername}}/certs"
    state: directory
  tags:
    - configure

- name: Fetch ca 
  ansible.builtin.fetch:
    src: "{{ er_home}}/bin/pki/ca.crt"
    dest: "{{ local_install_dir }}/{{ es_clustername}}/certs/{{ er_rootca }}.crt"
    flat: true
  when: not p.stat.exists
  tags:
    - configure

- name: Make sure the folder exists 
  delegate_to: localhost
  file:
    path: /etc/pki/ca-trust/source/anchors
    state: directory
  tags:
    - configure

- name: Copy PEM into folder 
  delegate_to: localhost
  copy:
    src: "{{ local_install_dir }}/{{ es_clustername}}/certs/{{ er_rootca }}.crt"
    dest: "/etc/pki/ca-trust/source/anchors/{{ er_rootca }}.crt"
  register: result
  when: not p.stat.exists
  tags:
    - configure

- name: Update CA Trust 
  delegate_to: localhost
  command: update-ca-trust
  when: not p.stat.exists
  tags:
    - configure

