---
# tasks file for configure

- name: Check for pki dir
  stat: path="{{ er_home}}/bin/pki"
  register: p

- name: init pki
  shell: 
    cmd: ./easyrsa init-pki
    chdir: "{{ er_home}}/bin"
  when: not p.stat.exists
  tags:
    - ca

- name: Create vars
  template:
    src: vars.j2
    dest: "{{ er_home}}/bin/vars"
  tags:
    - configure  

- name: build-ca
  shell: 
    cmd: ./easyrsa build-ca nopass
    chdir: "{{ er_home}}/bin"
  when: not p.stat.exists
  tags:
    - ca
