---
# tasks file for configure
- name: Configure myid
  template:
    src: "myid.j2"
    dest: "{{ zk_data_path}}/myid"
    owner: "{{ zk_user}}"
    group: "{{ zk_group}}"
  notify: restart  
  tags:
    - configure

- name: Configure server conf
  template:
    src: "{{ zk_config_file}}"
    dest: "{{ zk_conf}}/zookeeper.properties"
    owner: "{{ zk_user}}"
    group: "{{ zk_group}}"
  notify: restart  
  tags:
    - configure

- name: enable service 
  service: 
    name: "zookeeper"
    enabled: yes
    state: started
  tags:
    - configure
