---
# tasks file for requirements


- name: Copy file 
  copy:
    src: "{{ local_install_dir}}/GPG-KEY-elasticsearch"
    dest: "{{ remote_install_dir}}/GPG-KEY-elasticsearch"
  tags:
    - requirements  

- rpm_key:
    state: present
    key: "{{ remote_install_dir}}/GPG-KEY-elasticsearch"
  tags:
    - requirements  

- name: Remove file
  file:
    path: "{{ remote_install_dir}}/GPG-KEY-elasticsearch"
    state: absent         
  tags:
    - requirements  

- name: Install tar
  delegate_to: localhost
  yum:
     name: "tar"
     state: present        
  tags:
    - requirements  
