---
# tasks file for security


- name: elastic_pw
  delegate_to: localhost
  set_fact:
    pw: "{{ lookup('file', '{{ local_install_dir }}/{{ es_clustername }}-security') }}"
  when: es_security == true  
  tags:
    - security

- debug: msg="the value of pw is {{ pw }}"
  when: es_security == true  
  tags:
    - security

- name: elastic_pw
  delegate_to: localhost
  set_fact:
#    kibana: "{{ 'server1/database42'  | regex_search('server([0-9]+)/database([0-9]+)', '\\1', '\\2') }}"
    pw: "{{ pw | string   }}"
  when: es_security == true  
  tags:
    - security

- debug: msg="the value of pw is {{ pw }}"
  when: es_security == true  
  tags:
    - security

- name: elastic_pw
  delegate_to: localhost
  set_fact:
#    kibana: "{{ 'PASSWORD kibana_system = gndlttvbgjj3L3ncX1ti PASSWORD kibana = gndlttvbgjj3L3ncX1ti'  |  regex_search('kibana_system = ([a-zA-Z0-9]*)', '\\1') }}"
    kibana: "{{ pw  | regex_search('kibana_system = ([a-zA-Z0-9]*)', '\\1') | first}}"
  when: es_security == true  
  tags:
    - security

- debug: msg="the value of kibana is {{ kibana }}"
  when: es_security == true  
  tags:
    - security

- name: list  keystore
  shell: /usr/share/kibana/bin/kibana-keystore list
  register: keystore
  when: es_security == true
  tags:
    - security

- debug: var=keystore.stdout_lines
  when: es_security == true
  tags:
    - security


- name: Update xpack.security.transport.ssl.keystore.secure_password in keystore
  shell: printf "{{kibana}}"| /usr/share/kibana/bin/kibana-keystore add elasticsearch.password
  when: es_security == true and '"elasticsearch.password" not in keystore.stdout_lines'
  tags:
    - security

