---
# tasks file for security


- name: elastic_pw
  delegate_to: localhost
  set_fact:
    pw: "{{ lookup('file', '{{ local_install_dir }}/{{ es_clustername }}-security') }}"

- debug: msg="the value of pw is {{ pw }}"

- name: elastic_pw
  delegate_to: localhost
  set_fact:
#    kibana: "{{ 'server1/database42'  | regex_search('server([0-9]+)/database([0-9]+)', '\\1', '\\2') }}"
    pw: "{{ pw | string   }}"

- debug: msg="the value of pw is {{ pw }}"

- name: elastic_pw
  delegate_to: localhost
  set_fact:
#    kibana: "{{ 'PASSWORD kibana_system = gndlttvbgjj3L3ncX1ti PASSWORD kibana = gndlttvbgjj3L3ncX1ti'  |  regex_search('kibana_system = ([a-zA-Z0-9]*)', '\\1') }}"
    kibana: "{{ pw  | regex_search('kibana_system = ([a-zA-Z0-9]*)', '\\1') }}"

- debug: msg="the value of kibana is {{ kibana }}"
