---
# tasks file for firewall

- firewalld:
    port: "{{ es_host_port}}/tcp"
    permanent: true
    state: enabled
    immediate: true
  tags:
    - firewall  

- firewalld:
    port: "{{ es_transport_port}}/tcp"
    permanent: true
    state: enabled
    immediate: true
  tags:
    - firewall  
