---
# tasks file for install

- name: Copy file 
  copy:
    src: "{{ local_install_dir}}/elasticsearch-{{ elastic_version }}-x86_64.rpm"
    dest: "{{ remote_install_dir}}/elasticsearch-{{ elastic_version }}-x86_64.rpm"

- name: Populate service facts
  service_facts:    

- name: stop service 
  service: 
    name=elasticsearch
    state=stopped 
  when: ansible_facts.services['elasticsearch.service'] is defined    

- name: Install package.
  yum:
     name: "{{ remote_install_dir}}/elasticsearch-{{ elastic_version }}-x86_64.rpm"
     state: present        

- name: issue daemon-reload to pick up config changes
  systemd:
    daemon_reload: yes

- name: Remove file
  file:
    path: "{{ remote_install_dir}}/elasticsearch-{{ elastic_version }}-x86_64.rpm"
    state: absent     

- name: enable service 
  service: 
    name: elasticsearch
    enabled: yes
  tags:
    - install  
