---
# tasks file for install

- name: Copy file 
  copy:
    src: "{{ local_install_dir}}/repository-s3-"$version".zip"
    dest: "{{ remote_install_dir}}/repository-s3-"$version".zip"

- name: stop service 
  service: 
    name=elasticsearch
    state=stopped 

- elasticsearch_plugin:
    name: repository-s3
    state: present
    src: "file://{{ remote_install_dir}}/repository-s3-"$version".zip"