---
# tasks file for firewall
- firewalld:
    port: "{{ ka_port}}/tcp"
    permanent: true
    state: enabled
    immediate: true
  tags:
    - firewall  

- firewalld:
    port: "{{ ka_port_repl}}/tcp"
    permanent: true
    state: enabled
    immediate: true
  tags:
    - firewall  
