---
# tasks file for security

- name: Check for security info
  delegate_to: localhost
  stat:
    path: "{{ local_install_dir }}/{{ es_clustername }}/security"
  register: security
  when: es_security == true
  tags:
    - security


- name: Start service elasticsearch, if not started
  service:
    name: elasticsearch
    state: started    
  when: es_security == true
  tags:
    - security

- name: Run command if security does not exist
#  shell: printf "Y"|bin/elasticsearch-setup-passwords auto | grep PASSWORD > "/tmp/{{ es_clustername }}-security"
  shell: printf "Y"|bin/elasticsearch-setup-passwords auto  | grep PASSWORD
  register: ps
  args:
    chdir: "/usr/share/elasticsearch"
  when: security.stat.exists == false and es_security == true
  tags:
    - security

- debug: var=ps.stdout_lines
  when: security.stat.exists == false and es_security == true
  tags:
    - security

- name: save all facts to host specific file
  copy:
    content: "{{ ps.stdout_lines }}"
    dest: "/tmp/{{ es_clustername }}-security"
  when: security.stat.exists == false and es_security == true
  tags:
    - security

- name: Fetch security
  ansible.builtin.fetch:
    src: "/tmp/{{ es_clustername }}-security"
    dest: "{{ local_install_dir }}/{{ es_clustername }}/security"
    flat: true
  when: security.stat.exists == false and es_security == true
  tags:
    - security

- name: remove security
  file:
    path: "/tmp/{{ es_clustername }}-security"
    state: absent
  when: es_security == true  
  tags:
    - security 
