---
# tasks file for uninstall

- name: Populate service facts
  service_facts:    
  tags:
    - uninstall  

- name: stop service 
  service: 
    name: filebeat
    state: stopped 
  when: ansible_facts.services['filebeat.service'] is defined    
  tags:
    - uninstall  

- name: Uninstall package.
  yum:
     name: "filebeat*"
     state: absent       
  tags:
    - uninstall  

- name: Recursively remove directory
  file:
    path: /etc/filebeat
    state: absent
  tags:
    - uninstall  

- name: Recursively remove directory
  file:
    path: /var/log/filebeat
    state: absent    
  tags:
    - uninstall  
