---
# tasks file for disk

- name: task for creating volume group
  lvg:
      vg: "{{ volume_group }}"
      pvs: "{{ data_disk }}"
      pesize: 4

- name: Install lvm2 dependency
  package:
    name: lvm2
    state: present

- name: task for creating logical volume
  lvol:
      vg: "{{ volume_group }}"
      lv: "{{ logical_volume }}"
      size: 100%PVS
      force: yes

 - name: Create directory data1 if does not exist
   file:
      path: "{{ mount_logical_volume}}"
      state: directory
      mode: '0755'

- name: format the xfs filesystem
  filesystem:
    fstype: xfs
    dev: "/dev/{{ volume_group }}/{{ logical_volume }}"


- name: mount the lv on 
  mount:
    path: "{{ mount_logical_volume }}"
    src: "/dev/{{ volume_group }}/{{ logical_volume }}"
    fstype: xfs
    state: mounted      