---
# tasks file for configure


- name: create data directory for {{ es_clustername}}
  delegate_to: localhost
  file:
    path: "{{ local_install_dir}}/{{ es_clustername}}/certs"
    state: directory
  tags:
    - configure  


- name: create data directory
  file:
    path: "{{ data_path}}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
  notify:
    - restart
  tags:
    - configure  


- name: Configure elasticsearch.yml
  template:
    src: "{{ es_elasticsearch_yml }}"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: elasticsearch
    group: elasticsearch
  notify:
    - restart
  tags:
    - configure  
