---
# tasks file for install

- name: Install ntpd
  yum:
    name: 
      - chrony
    state: present  
  tags:
    - install  

- name: enable service 
  service: 
    name: chronyd
    enabled: true
    state: started
  tags:
    - install  