---
# tasks file for install

- name: Populate service facts
  service_facts:    
  tags:
    - install  

- name: stop service 
  service: 
    name: rsyslog
    state: stopped 
  when: ansible_facts.services['rsyslog.service'] is defined    
  tags:
    - install  

- name: Install package.
  yum:
     name: "rsyslog"
     state: present        
  tags:
    - install  

- name: issue daemon-reload to pick up config changes
  systemd:
    daemon_reload: yes
  tags:
    - install  

- name: enable service 
  service: 
    name: rsyslog
    enabled: yes
  tags:
    - install  
