---

- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present
  tags:
    - install

- name: Start and enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes
  tags:
    - install

- name: Configure firewalld on master nodes
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    immediate: true
  with_items: '{{ k8s_master_ports }}'
  when: "k8_role_master == true"
  tags:
    - install

- name: Configure firewalld on worker nodes
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    immediate: true
  with_items: '{{ k8s_worker_ports }}'
  when: (k8_role_node == true or k8_role_worker ==
   true)
  tags:
    - install

- name: Add the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present    
  when: ("k8_role_master == true" or k8_role_worker == true)
  tags:
    - install

- name: bridge-nf-call-iptables
  shell: 
    cmd: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
  when: ("k8_role_master == true" or k8_role_worker == true)
  tags:
    - install


